### PR TITLE
Support for Habitica.com

### LINKED ISSUE #36: habitrpg.com switch to habitica.com
Habitrpg.com is switching to habitica.com as of 7/31, and the chat extension doesn't work over there yet.  It looks like it might just be a quick fix to the matching urls and account linking url?

Thanks for making a great extension - it's been super useful so far!
~studentSeekingDiscipline

### PR DESCRIPTION
**Pull request by crookedneighbor**
Fixes #36

### CODE REVIEW

**Comment by crookedneighbor** [comment]
@Horacious Sorry to bug you about this, but do you know when you'll be able to review this and upload it to the Chrome store?

**Comment by FriendlyPopo** [comment]
@crookedneighbor I missed the notification! Thanks for the reminder. Will absolutely update this afternoon.

**Comment by FriendlyPopo** [comment]
Chrome store has been updated (so has master branch). Sorry for the delay!

**Comment by crookedneighbor** [comment]
No worries, recently, Github email notifications have been pretty flakey for me too.

**Pull request merged**
